Shouldo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls'))
]

tasks/urls.py
# Django imports
from django.urls import path

# My App imports
from tasks.views import task_views

app_name = 'tasks'

urlpatterns = [
    path(route='', view=task_views.get_all_tasks, name='index'),
    path(route='tasks/create', view=task_views.create_task, name='create'),
    path(route='tasks/update/<int:id>', view=task_views.update_task, name='update'),
    path(route='tasks/delete/<int:id>', view=task_views.delete_task, name='delete'),
    path(route='tasks/task-detail/<int:id>', view=task_views.get_task, name='detail'),

    # json get request
    path(route='tasks/get-task-json/<int:id>', view=task_views.get_task_json)
]

tasks/models/task_model.py
# Django imports
from django.db import models
from django.utils import timezone


class Task(models.Model):
    title = models.CharField(max_length=100, blank=False)
    detail = models.TextField(blank=False)
    due_date = models.DateField(blank=False)
    created_at = models.DateTimeField(default=timezone.now(), editable=False)
    updated_at = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)

tasks/forms/create_task_form.py
# Django imports
from django import forms

# My App imports
from tasks.models.task_model import Task


class CreateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'detail', 'due_date']
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'placeholder': 'Enter title',
                    'class': 'form-control form-control-line'
                }
            ),
            'detail': forms.Textarea(
                attrs={
                    'placeholder': 'Enter detail',
                    'class': 'form-control form-control-line'
                }
            ),
            'due_date': forms.DateInput(
                attrs={
                    'placeholder': 'Schedule date',
                    'class': 'form-control form-control-line',
                    'type': 'date'
                }
            ),
        }

tasks/forms/update_task_form.py
# Django imports
from django import forms

# My App imports
from tasks.models.task_model import Task


class UpdateTaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ['title', 'detail', 'due_date']

        widgets = {
            'title': forms.TextInput(
                attrs={
                    'placeholder': 'Enter title',
                    'class': 'form-control form-control-line',
                    'name': 'title',
                    'id': 'title'
                }
            ),
            'detail': forms.Textarea(
                attrs={
                    'placeholder': 'Enter detail',
                    'class': 'form-control form-control-line',
                    'name': 'detail',
                    'id': 'detail'
                }
            ),
            'due_date': forms.DateInput(
                attrs={
                    'placeholder': 'Schedule date',
                    'class': 'form-control form-control-line',
                    'type': 'date',
                    'name': 'due_date',
                    'id': 'due_date'
                }
            ),
        }

tasks/views/task_views.py
# Core Python imports
import json

# Django imports
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import JsonResponse

# My App imports
from tasks.forms.create_task_form import CreateTaskForm
from tasks.forms.update_task_form import UpdateTaskForm
from tasks.models.task_model import Task


# create task
def create_task(request):
    try:
        form = CreateTaskForm(data=request.POST)
        form.is_valid()
        new_task = form.save()
        messages.success(request, f"Task '{new_task.title}' created successfully!")
    except Exception as e:
        messages.error(request, e)

    return redirect('tasks:index')


# delete task
def delete_task(request, id):
    try:
        task = Task.objects.get(pk=id)
        task.is_deleted = True
        task.save()
        messages.success(request, f"Task '{task.title}' deleted successfully!")
    except Exception as e:
        messages.error(request, e)

    return redirect('tasks:index')


# update task
def update_task(request, id):
    if request.method == 'POST':
        try:
            task = Task.objects.get(pk=id)
            form = UpdateTaskForm(data=request.POST, instance=task)
            form.save()
            messages.success(request, 'Task has been updated successfully!')
        except Exception as e:
            messages.error(request, e)

        return redirect('tasks:index')


# retrieve all tasks
def get_all_tasks(request):
    tasks = Task.objects.filter(is_deleted=False).order_by('id')
    create_task_form = CreateTaskForm()
    update_task_form = UpdateTaskForm()

    context = {
        'tasks': tasks,
        'create_task_form': create_task_form,
        'update_task_form': update_task_form
    }
    return render(request=request, template_name='tasks/index.html', context=context)


# show single task
def get_task(request, id):
    task = Task.objects.filter(pk=id).first()

    context = {
        'task': task
    }
    return render(request=request, template_name='tasks/task-detail.html', context=context)


# get task as json
def get_task_json(request, id):
    task = Task.objects.get(pk=id)
    task_dict = {
        'id': task.id,
        'title': task.title,
        'detail': task.detail,
        'due_date': task.due_date
    }

    return JsonResponse(data=task_dict, safe=True)

tasks/templates/tasks/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shouldo | {% block title %}{% endblock title %}</title>

    {% block stylesheets %}
        <link href="{% static 'tasks/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% endblock stylesheets %}
</head>

<body>

{% block header %}
    <div class="container">
    <div class="card card-body bg-success" style="margin-top: 10px">
        <div style="text-align: center">
            <h2 style="color: white">ToDo App</h2>
            <h3 style="color: white">Create your tasks with ease, achieve them like a Champ!</h3>
        </div>
    </div>
    <div>
    <br/><br/>
{% endblock header %}

<!-- Messages -->
{% block messages %}
    <div class="row">
        <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}
                    <div class="text-center font-weight-bold alert alert-dismissible fade show
                       {% if message.level_tag == 'error' %}
                       alert-danger
                       {% else %}
                       alert-{{ message.tags }}
                       {% endif %}">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock messages %}
{% block content %}

{% endblock content %}
</div>
</div>
{% block scripts %}
    <script src="{% static 'tasks/bootstrap/js/jquery.js' %}" type="text/javascript"></script>
    <script src="{% static 'tasks/bootstrap/js/bootstrap.js' %}" type="text/javascript"></script>
{% endblock scripts %}
</body>
</html>

tasks/templates/tasks/index.html
{% extends 'tasks/base.html' %}
{% load static %}
{% block title %} List of Tasks {% endblock title %}
{% block content %}

    <button style="float: right" class="btn btn-success" data-toggle="modal" data-target="#exampleModal"><i
            class="fa fa-plus"></i> Add task
    </button>
    <h3>All Tasks</h3>
    <table class="table table-striped table-bordered">
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Due Date</th>
            <th>Created at</th>
            <th>Action</th>
        </tr>
        {% for task in tasks %}
            <tr>
                <td>{{ task.id }}</td>
                <td>{{ task.title }}</td>
                <td>{{ task.due_date }}</td>
                <td>{{ task.created_at }}</td>
                <td>
                    <a href="{% url 'tasks:detail' task.id %}"><span class="badge badge-info"><i
                            class="fa fa-eye"></i> View</span></a>
                    <a id="{{ task.id }}" class="update-task" href="javascript: void(0)"><span
                            class="badge badge-warning"
                            data-target="#updateTaskModal" data-toggle="modal">
                        <i class="fa fa-pencil"> Edit</i></span></a>
                    <a id="{{ task.id }}" class="delete-task" href="javascript: void(0)"><span
                            class="badge badge-danger"><i class="fa fa-trash"> Delete</i>
                    </span></a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <!-- Add Task Form Modal -->
    <div id="exampleModal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form action="{% url 'tasks:create' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-header">
                        <h3>Add Task</h3>
                    </div>
                    <div class="modal-body">
                        {{ create_task_form }}
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-success" type="submit">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Update Task Form Modal -->
    <div id="updateTaskModal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form id="update_task_form" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-header">
                        <h3>Update Task</h3>
                    </div>
                    <div class="modal-body">
                        {{ update_task_form }}
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-success" type="submit">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}
{% block scripts %}
    {{ block.super }}

    <!-- Sweet Alert -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>

    <!-- My App -->
    <script src="{% static 'tasks/task.js' %}"></script>
{% endblock scripts %}

tasks/templates/tasks/task-detail.html
{% extends 'tasks/base.html' %}

{% block content %}
 <h3>Title</h3>
 {{ task.title }} <br/>
 <h3>Detail</h3>
 {{ task.detail }}
{% endblock content %}